/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fplayer_jni_PlayControl */

#ifndef _Included_com_example_fplayer_jni_PlayControl
#define _Included_com_example_fplayer_jni_PlayControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fplayer_jni_PlayControl
 * Method:    startPlayer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_fplayer_jni_PlayControl_startPlayer
  (JNIEnv *, jobject, jstring,jobject);

#ifdef __cplusplus
}
#endif
#endif
